<?php
/**
 * InstallmentPlanEventType
 *
 * PHP version 5
 *
 * @category Class
 * @package  SplititSdkClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SplititSdkClient\Model;
use \SplititSdkClient\ObjectSerializer;

/**
 * InstallmentPlanEventType Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  SplititSdkClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InstallmentPlanEventType
{
    /**
     * Possible values of this enum
     */
    const SECURE_AUTH_SUCCEEDED = 'SecureAuthSucceeded';
    const SECURE_AUTH_FAILED = 'SecureAuthFailed';
    const CHARGE_SUCCEEDED = 'ChargeSucceeded';
    const CHARGE_FAILED = 'ChargeFailed';
    const REFUND_SUCCEEDED = 'RefundSucceeded';
    const REFUND_FAILED = 'RefundFailed';
    const FULL_CAPTURE_SUCCEEDED = 'FullCaptureSucceeded';
    const FULL_CAPTURE_FAILED = 'FullCaptureFailed';
    const PLAN_CREATED_SUCCEEDED = 'PlanCreatedSucceeded';
    const PLAN_CREATED_FAILED = 'PlanCreatedFailed';
    const PLAN_APPROVED_SUCCEEDED = 'PlanApprovedSucceeded';
    const PLAN_APPROVED_FAILED = 'PlanApprovedFailed';
    const PLAN_UPDATED_SUCCEEDED = 'PlanUpdatedSucceeded';
    const PLAN_UPDATED_FAILED = 'PlanUpdatedFailed';
    const PLAN_CANCELLED_SUCCEEDED = 'PlanCancelledSucceeded';
    const PLAN_CANCELLED_FAILED = 'PlanCancelledFailed';
    const CUSTOMER_CREDIT_CARD_UPDATE_SUCCEEDED = 'CustomerCreditCardUpdateSucceeded';
    const CUSTOMER_CREDIT_CARD_UPDATE_FAILED = 'CustomerCreditCardUpdateFailed';
    const CUSTOMER_DETAILS_UPDATE_SUCCEEDED = 'CustomerDetailsUpdateSucceeded';
    const CUSTOMER_DETAILS_UPDATE_FAILED = 'CustomerDetailsUpdateFailed';
    const START_INSTALLMENTS_SUCCEEDED = 'StartInstallmentsSucceeded';
    const START_INSTALLMENTS_FAILED = 'StartInstallmentsFailed';
    const PLAN_CLEARED = 'PlanCleared';
    const PLAN_DELAYED = 'PlanDelayed';
    const PLAN_RECOVERED = 'PlanRecovered';
    const PLAN_SECURED_AUTH_REMINDER_SHOULD_BE_SENT = 'PlanSecuredAuthReminderShouldBeSent';
    const RETRY_SUCCEEDED = 'RetrySucceeded';
    const RETRY_FAILED = 'RetryFailed';
    const PLAN_DELETED = 'PlanDeleted';
    const REFUND_COMPLETED = 'RefundCompleted';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SECURE_AUTH_SUCCEEDED,
            self::SECURE_AUTH_FAILED,
            self::CHARGE_SUCCEEDED,
            self::CHARGE_FAILED,
            self::REFUND_SUCCEEDED,
            self::REFUND_FAILED,
            self::FULL_CAPTURE_SUCCEEDED,
            self::FULL_CAPTURE_FAILED,
            self::PLAN_CREATED_SUCCEEDED,
            self::PLAN_CREATED_FAILED,
            self::PLAN_APPROVED_SUCCEEDED,
            self::PLAN_APPROVED_FAILED,
            self::PLAN_UPDATED_SUCCEEDED,
            self::PLAN_UPDATED_FAILED,
            self::PLAN_CANCELLED_SUCCEEDED,
            self::PLAN_CANCELLED_FAILED,
            self::CUSTOMER_CREDIT_CARD_UPDATE_SUCCEEDED,
            self::CUSTOMER_CREDIT_CARD_UPDATE_FAILED,
            self::CUSTOMER_DETAILS_UPDATE_SUCCEEDED,
            self::CUSTOMER_DETAILS_UPDATE_FAILED,
            self::START_INSTALLMENTS_SUCCEEDED,
            self::START_INSTALLMENTS_FAILED,
            self::PLAN_CLEARED,
            self::PLAN_DELAYED,
            self::PLAN_RECOVERED,
            self::PLAN_SECURED_AUTH_REMINDER_SHOULD_BE_SENT,
            self::RETRY_SUCCEEDED,
            self::RETRY_FAILED,
            self::PLAN_DELETED,
            self::REFUND_COMPLETED,
        ];
    }
}


