<?php
/**
 * InstallmentStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  SplititSdkClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SplititSdkClient\Model;
use \SplititSdkClient\ObjectSerializer;

/**
 * InstallmentStatus Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  SplititSdkClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InstallmentStatus
{
    /**
     * Possible values of this enum
     */
    const NONE = 'None';
    const WAITING_FOR_PROCESS_DATE = 'WaitingForProcessDate';
    const FINISHED = 'Finished';
    const DELETED = 'Deleted';
    const STOPPED = 'Stopped';
    const CANCELED = 'Canceled';
    const AWAITING_CAPTURE = 'AwaitingCapture';
    const AWAITING_VOID = 'AwaitingVoid';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::WAITING_FOR_PROCESS_DATE,
            self::FINISHED,
            self::DELETED,
            self::STOPPED,
            self::CANCELED,
            self::AWAITING_CAPTURE,
            self::AWAITING_VOID,
        ];
    }
}


