<?php
/**
 * UserType
 *
 * PHP version 5
 *
 * @category Class
 * @package  SplititSdkClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * splitit-web-api-public-sdk
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SplititSdkClient\Model;
use \SplititSdkClient\ObjectSerializer;

/**
 * UserType Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  SplititSdkClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserType
{
    /**
     * Possible values of this enum
     */
    const USER = 'User';
    const APPLICATIVE_USER = 'ApplicativeUser';
    const USER_WITH_ACTION_ITEM = 'UserWithActionItem';
    const ADMIN_USER = 'AdminUser';
    const PIS_USER = 'PisUser';
    const API_USER = 'ApiUser';
    const PIS_MEMBER = 'PisMember';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::USER,
            self::APPLICATIVE_USER,
            self::USER_WITH_ACTION_ITEM,
            self::ADMIN_USER,
            self::PIS_USER,
            self::API_USER,
            self::PIS_MEMBER,
        ];
    }
}


